name: advanced_dio_helper
description: "A complete advanced Dio helper for Flutter with token management, logging, retry, and repository architecture."
version: 1.0.0
homepage: https://github.com/musamakhalid03/advanced_dio_helper




environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive_flutter: ^1.1.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
